### ISSUE TITLE
YAML linting

### ISSUE THREAD

**Issue by coderanger** [chef/chefstyle#23]
Do we want to look at adding something like `yaml-lint` as a standard for YAML files?

Ref https://github.com/portertech/kitchen-docker/pull/183

**Comment by thommay** [comment]
i'm kind of eh, especially since t-k doesn't use chefstyle.

**Comment by thommay** [comment]
if we were talking about chefcop for cookbooks then yes, absolutely.

**Comment by coderanger** [comment]
I looked in to this a bit yesterday, there is no way to do any non-Ruby stuff in RuboCop even with custom cops. We could look at adding a shared Rake task to this repo that runs more than just `chefstyle` though.

**Comment by lamont-granquist** [comment]
but from the README:

"It is not meant for consumption by cookbooks or for any general purpose uses. It is not intended for any audience outside of chef core ruby development."

if we forked this into chefcop or cookstyle that was designed to be baked into the chef-dk and applied by default to cookbooks, then i'd agree we could look at something like that...

**Comment by coderanger** [comment]
This isn't related to cookbook testing, there are a ton of YAML files (mostly testing related) in the Chef codebase and we should probably decide on some kind of standard for them.

**Comment by lamont-granquist** [comment]
still feel like its out of scope for this repo.  not a terrible idea in general, but not convinced at all that this repo should expand its scope that way, or that yaml linting is the biggest issue we've got.

**Comment by coderanger** [comment]
In theory whatever standard we pick should apply to everything using `chefstyle`, so it would seem like any lint-related stuff should probably be collected here.

**Comment by lamont-granquist** [comment]
So, I guess I'd be more in favor of this as a PR rather than an issue.  If you've got an itch you want to scratch then go ahead and scratch it.  Difference is that I'd rather not spend a lot of time maintaining YAML linting right now, so when its couched in "We" terms I'm more disinclined -- when its couched more in terms of whacking green merge buttons I'm more on the spectrum from disinterested to a bit inclined...
